### PR TITLE
fix parsing of osm wiki map-features tables to close #419

### LINKED ISSUE #419: available_tags() problem
I face the problem with `available_tags( )` function.

When using the syntax 
`available_tags("amenity")`

I got the following 

Warning message:
In (function (..., deparse.level = 1)  :
  number of columns of result is not a multiple of vector length (arg 1)

Any suggestions on what is wrong? Thanks in advance.

### PR DESCRIPTION
**Pull request by mpadge**

### CODE REVIEW

File: R/features.R [hunk 1]
```diff
@@ -157,7 +157,12 @@ tags_from_tables <- function (pg) {
         if (identical (names (i) [1:2], c ("Key", "Value"))) {
             res <- i [, 1:2]
         } else {
-            res <- do.call (rbind, strsplit (i [[1]], split = "="))
+            # "Key" has value, generally "<key>=*", but sometimes multiple
+            # entries separated by commas.
+            keys_i <- unlist (strsplit (i [[1]], ","))
+            keys_i <- grep ("\\=", keys_i, value = TRUE)
+            keys_i <- gsub ("^\\s*|\\s*$", "", keys_i)
```
Comment (jmaspons) [inline R/features.R:164]:
```suggestion
            keys_i <- trimws (keys_i)
```

**Review by jmaspons — COMMENTED** [review]
Seems that work. Just a minor change. Sorry for the late review

**Comment by mpadge** [comment]
Oh sorry, i merged already. Can you add that separately, please? Thanks

File: R/features.R (hunk 1 above)
Comment (jmaspons) [reply R/features.R:164]: Committed in 99477b2ac0625a8db701b91a0778be8c59a3030e

**Comment by jmaspons** [comment]
I just committed the change it was a very minor and a matter of style
